baseURL = "https://p1xxxel.github.io/"
title = "Shell"
# author = "Yukuro"
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[Params]
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = "p1xel's blog"
  [Params.Terminal]
  # Note: color schema
  # Note: You can choose between
  # Note: ["monokai", "powershell", "gruvbox_light", "gruvbox_dark", "solarized_light", "solarized_dark", "ubuntu", "retro"]
  schema = "solarized_dark"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > use = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "p1xel"
  pcName = "arch"
  workDir = "writeups"
  profile = "profile.txt"

  # Note: speed at which text is displayed on the terminal
  # Note: if set to 0, typing animation will be disabled
  terminalDelay = 5

  # Note: speed at which text is displayed on the activity pages
  # Note: if set to 0, typing animation will be disabled
  activityDelay = 0

  description = """
  Hi I am p1xel!
  Nice to meet you!

  """

  # Note: If you want to use a Markdown file, you can use the following
  # description = "/description.md"
  # Note: and put the description.md in /content/description.md

  [Params.Tree]
  use = true
  folderName = "my_activity"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    ["Hackthebox Pit Writeup", "/posts/pit-writeup.md"],
    ["Hackthebox Explore Writeup", "/posts/explore-writeup.md"],
    ["Hackthebox Cap Writeup", "/posts/cap-writeup.md"],
    ["Tryhackme CMSpit Writeup - NoSQL to RCE in cockpit", "/posts/CMSpit-writeup.md"],
  ]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.85.0"
